### PR TITLE
Schedule draft (start/end times)

### PR DESCRIPTION
**Pull request by csoneson**
Adding rough start/end times to help people booking travel and accommodation.

### CODE REVIEW

**Comment by mdozmorov** [comment]
Hi Charlotte, can you check why this simple edit causes Netlify to fail to build the site? I'll also check asap.

**Comment by csoneson** [comment]
I'm also quite puzzled...trying to decode the Netlify output...

**Comment by csoneson** [comment]
@mdozmorov I'm not sure it has anything to do with the actual changes - in https://github.com/Bioconductor/EuroBioC2022/pull/12 I just added a space, and it also fails. Could it be a dependency that needs to be updated or something like that?

**Comment by mdozmorov** [comment]
I cleared cache and restarted deployment - same error. Will be looking into it. In the midst of BioC conference, a bit short of time now.

**Pull request merged**
